name: Code Quality Checks

on:
  - push
  - pull_request

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Clippy
        run: cargo clippy -- -D warnings

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check formatting
        run: cargo fmt -- --check

  selene:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Selene
        working-directory: plugin
        run: |
          cargo install selene
          selene .

  StyLua:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: StyLua
        working-directory: plugin
        run: |
          cargo install stylua --features luau 
          stylua . --check
